import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f5f5f5',
  },
  courseContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    elevation: 3, 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'green',
    marginLeft: 40,
    top: 10,
  },
  price: {
    marginTop: 10,
    marginLeft: 145,
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginTop: 10,
  },
  containerInfoScreen: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageInfo: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderRadius: 10,
    marginBottom: 20,
  },
  descriptionInfo: {
    fontSize: 18,
    fontWeight: 'semibold',
    color: '#333',
    marginLeft: 40,
    marginRight: 40,
    marginBottom: 10,
  },
  priceInfo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'green',
    textAlign: 'center',
    marginLeft: 220,
  },
  containerInfo: {
    backgroundColor: 'gray',
    bottom:0,
    opacity: 0.3,
    width: '100%',
    padding: 18,
    elevation: 3,
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  containerTab: {
    backgroundColor: 'green',
    width: '100%',
    padding: 10, 
  },
  buttonInfo: {
    backgroundColor: '#FFCA1A',
    width: '50%',
    height: 50,
    justifyContent: 'center', 
    alignItems: 'center',
    marginLeft: 90,
    borderRadius: 5, 
  },
  headerStyle: {
    backgroundColor: 'green',
  },
  headerTintColor: '#fff',
  headerTitleStyle: {
    fontWeight: 'bold',
  },
  containerCardInformation: {
    backgroundColor: '#f5f5f5',
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    width: '92%',
    backgroundColor: '#fff',
    left: 16,
    borderRadius: 10,
    width: '92%',
  },
  coursCardInfo: {
    top: 18,
    backgroundColor: '#f5f5f5',
  },
  itemTitle: {
    fontSize: 16,
    color: '#333',
  },
  itemPrice: {
    fontSize: 16,
    color: '#333',
  },
  totalContainer: {
    flexDirection: 'row',
    top: 16,
    padding: 20,
    left: 16,
    borderRadius: 10,
    width: '92%',
    backgroundColor: '#fff',
  },
  totalText: {
    bottom: 10,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  dateText: {
    bottom: 2,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 20,
  },
  containerCardPrice: {
    backgroundColor: '#f5f5f5',
  },
  itemContainerCard: {
    top: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomColor: '#ddd',
  },
  itemPriceCard: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  buttonPrice: {
    backgroundColor: '#e69b00',
    fontSize: 16,
    borderRadius: 10,
  },
  totalContainerCard: {
    width: '92%',
    height: 50,
    flexDirection: 'row',
    marginTop: 20,
    left: 16,
    borderRadius: 10,
    justifyContent: 'space-around',
    backgroundColor: '#fff',
  },
  totalTextCard: {
    top: 12,
    left: 14,
    fontSize: 16,
    fontWeight: 'semibold',
    color: '#333',
  },
  priceTextCart: {
    bottom: 16,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 20,
    alignSelf: 'flex-end',
    right:4 ,
  },
  deleteIcon: {
    top: 8, 
    right: 2,
  },
});